// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechNormBlazor.Data;

#nullable disable

namespace TechNormBlazor.Migrations
{
    [DbContext(typeof(TechNormDbContext))]
    [Migration("20260515163136_AddSourceEventCount")]
    partial class AddSourceEventCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechNormBlazor.Data.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.CalculationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<int?>("CalculatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("calculated_by");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Metrics")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedBy");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RouteId");

                    b.ToTable("calculation_history", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("text")
                        .HasColumnName("sha256_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.EventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int?>("SourceDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("source_document_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SourceDocumentId");

                    b.ToTable("event_logs", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.MaterialNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumptionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption_rate");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<int>("RouteStepId")
                        .HasColumnType("integer")
                        .HasColumnName("route_step_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RouteStepId");

                    b.ToTable("material_norms", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Characteristics")
                        .HasColumnType("jsonb")
                        .HasColumnName("characteristics");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.RouteStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("OperationId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_id");

                    b.Property<JsonDocument>("Parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<int?>("ParentStepId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_step_id");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<int>("SequenceNum")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_num");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ParentStepId");

                    b.HasIndex("RouteId");

                    b.ToTable("route_steps", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.TechRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("ProcessTree")
                        .HasColumnType("jsonb")
                        .HasColumnName("process_tree");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("SourceEventCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("tech_routes", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.TimeNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<decimal>("NormValue")
                        .HasColumnType("numeric")
                        .HasColumnName("norm_value");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<int>("RouteStepId")
                        .HasColumnType("integer")
                        .HasColumnName("route_step_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RouteStepId");

                    b.ToTable("time_norms", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.AuditLog", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.CalculationHistory", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.User", "Calculator")
                        .WithMany()
                        .HasForeignKey("CalculatedBy");

                    b.HasOne("TechNormBlazor.Data.Models.Document", null)
                        .WithMany("CalculationHistories")
                        .HasForeignKey("DocumentId");

                    b.HasOne("TechNormBlazor.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("TechNormBlazor.Data.Models.TechRoute", "Route")
                        .WithMany("CalculationHistories")
                        .HasForeignKey("RouteId");

                    b.Navigation("Calculator");

                    b.Navigation("Product");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Document", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.User", "Uploader")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.EventLog", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("TechNormBlazor.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("TechNormBlazor.Data.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.HasOne("TechNormBlazor.Data.Models.Document", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId");

                    b.Navigation("Creator");

                    b.Navigation("Product");

                    b.Navigation("Resource");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.MaterialNorm", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.Material", "Material")
                        .WithMany("MaterialNorms")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNormBlazor.Data.Models.RouteStep", "RouteStep")
                        .WithMany("MaterialNorms")
                        .HasForeignKey("RouteStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("RouteStep");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.RouteStep", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.Operation", "Operation")
                        .WithMany("RouteSteps")
                        .HasForeignKey("OperationId");

                    b.HasOne("TechNormBlazor.Data.Models.RouteStep", "ParentStep")
                        .WithMany("ChildSteps")
                        .HasForeignKey("ParentStepId");

                    b.HasOne("TechNormBlazor.Data.Models.TechRoute", "Route")
                        .WithMany("Steps")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("ParentStep");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.TechRoute", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.User", "Creator")
                        .WithMany("TechRoutes")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("TechNormBlazor.Data.Models.Product", "Product")
                        .WithMany("TechRoutes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.TimeNorm", b =>
                {
                    b.HasOne("TechNormBlazor.Data.Models.Resource", "Resource")
                        .WithMany("TimeNorms")
                        .HasForeignKey("ResourceId");

                    b.HasOne("TechNormBlazor.Data.Models.RouteStep", "RouteStep")
                        .WithMany("TimeNorms")
                        .HasForeignKey("RouteStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("RouteStep");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Document", b =>
                {
                    b.Navigation("CalculationHistories");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Material", b =>
                {
                    b.Navigation("MaterialNorms");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Operation", b =>
                {
                    b.Navigation("RouteSteps");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Product", b =>
                {
                    b.Navigation("TechRoutes");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.Resource", b =>
                {
                    b.Navigation("TimeNorms");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.RouteStep", b =>
                {
                    b.Navigation("ChildSteps");

                    b.Navigation("MaterialNorms");

                    b.Navigation("TimeNorms");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.TechRoute", b =>
                {
                    b.Navigation("CalculationHistories");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TechNormBlazor.Data.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Documents");

                    b.Navigation("TechRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
